"""adicionar_campo_foto_url_usuarios

Revision ID: 092a11b55114
Revises: 43ace6576e6c
Create Date: 2025-08-20 16:22:40.649747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092a11b55114'
down_revision: Union[str, None] = '43ace6576e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('itens_catalogo_processo_id_fkey', 'itens_catalogo', type_='foreignkey')
    op.drop_column('itens_catalogo', 'marca')
    op.drop_column('itens_catalogo', 'processo_id')
    op.drop_column('itens_catalogo', 'embalagem')
    op.add_column('users_safs', sa.Column('foto_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_safs', 'foto_url')
    op.add_column('itens_catalogo', sa.Column('embalagem', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('itens_catalogo', sa.Column('processo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('itens_catalogo', sa.Column('marca', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_foreign_key('itens_catalogo_processo_id_fkey', 'itens_catalogo', 'planejamento_aquisicao', ['processo_id'], ['id'])
    # ### end Alembic commands ###
