"""Remover campo processo_id e is_responsavel_tecnico

Revision ID: 123abc456def
Revises: f44eabf6633e
Create Date: 2025-01-21 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123abc456def'
down_revision: Union[str, None] = 'f44eabf6633e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover coluna is_responsavel_tecnico da tabela users_safs
    op.drop_column('users_safs', 'is_responsavel_tecnico')
    
    # Remover coluna processo_id da tabela itens_catalogo
    op.drop_column('itens_catalogo', 'processo_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restaurar coluna processo_id na tabela itens_catalogo
    op.add_column('itens_catalogo', sa.Column('processo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_itens_catalogo_processo_id', 'itens_catalogo', 'planejamento_aquisicao', ['processo_id'], ['id'])
    
    # Restaurar coluna is_responsavel_tecnico na tabela users_safs
    op.add_column('users_safs', sa.Column('is_responsavel_tecnico', sa.BOOLEAN(), nullable=True, default=False))
    
    # ### end Alembic commands ###