"""foreignKey nas tabelas

Revision ID: 1dea829283ae
Revises: 9c27e61cdef9
Create Date: 2025-07-09 15:29:13.270721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dea829283ae'
down_revision: Union[str, None] = '9c27e61cdef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_catalogo', sa.Column('comprador_id', sa.Integer(), nullable=True))
    op.add_column('itens_catalogo', sa.Column('controlador_id', sa.Integer(), nullable=True))
    op.add_column('itens_catalogo', sa.Column('processo_id', sa.Integer(), nullable=True))
    op.add_column('itens_catalogo', sa.Column('observacao', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'itens_catalogo', 'users_safs', ['comprador_id'], ['id'])
    op.create_foreign_key(None, 'itens_catalogo', 'users_safs', ['controlador_id'], ['id'])
    op.create_foreign_key(None, 'itens_catalogo', 'planejamento_aquisicao', ['processo_id'], ['id'])
    op.drop_column('itens_catalogo', 'comprador')
    op.drop_column('itens_catalogo', 'controlador')
    op.add_column('planejamento_aquisicao', sa.Column('observacao', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planejamento_aquisicao', 'observacao')
    op.add_column('itens_catalogo', sa.Column('controlador', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('itens_catalogo', sa.Column('comprador', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itens_catalogo', type_='foreignkey')
    op.drop_constraint(None, 'itens_catalogo', type_='foreignkey')
    op.drop_constraint(None, 'itens_catalogo', type_='foreignkey')
    op.drop_column('itens_catalogo', 'observacao')
    op.drop_column('itens_catalogo', 'processo_id')
    op.drop_column('itens_catalogo', 'controlador_id')
    op.drop_column('itens_catalogo', 'comprador_id')
    # ### end Alembic commands ###
