"""inseri unic=true na classe planejamento aquisição

Revision ID: 3061c9344fb0
Revises: 6558fab46e4d
Create Date: 2025-07-19 14:12:08.625934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3061c9344fb0'
down_revision: Union[str, None] = '6558fab46e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'planejamento_aquisicao', ['numero_processo_planejamento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planejamento_aquisicao', type_='unique')
    # ### end Alembic commands ###
