"""inseri unic=true no campo copra centralizada

Revision ID: 3d9eec300d52
Revises: 3061c9344fb0
Create Date: 2025-07-19 14:39:53.113355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9eec300d52'
down_revision: Union[str, None] = '3061c9344fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'planejamento_aquisicao', ['numero_processo_compra_centralizada'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planejamento_aquisicao', type_='unique')
    # ### end Alembic commands ###
