"""Sincronizar modelos com banco de dados

Revision ID: 472cd77349fd
Revises: 5a04f046d1c4
Create Date: 2025-08-11 10:30:33.641817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472cd77349fd'
down_revision: Union[str, None] = '5a04f046d1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_processo',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens_catalogo.id'], name='fk_item_processo_item_id'),
    sa.ForeignKeyConstraint(['processo_id'], ['planejamento_aquisicao.id'], name='fk_item_processo_processo_id'),
    sa.PrimaryKeyConstraint('item_id', 'processo_id')
    )
    
    # Adicionar colunas com valores padrão temporários para evitar erro de NOT NULL
    op.add_column('itens_catalogo', sa.Column('unidade', sa.String(length=20), nullable=True))
    op.add_column('itens_catalogo', sa.Column('marca', sa.String(length=60), nullable=True))
    op.add_column('itens_catalogo', sa.Column('embalagem', sa.String(length=60), nullable=True))
    
    # Atualizar registros existentes com valor padrão
    op.execute("UPDATE itens_catalogo SET unidade = 'ULOG' WHERE unidade IS NULL")
    
    # Tornar a coluna NOT NULL após popular os dados
    op.alter_column('itens_catalogo', 'unidade', nullable=False)
    
    op.add_column('planejamento_aquisicao', sa.Column('unidade', sa.String(length=60), nullable=True))
    # Atualizar registros existentes com valor padrão
    op.execute("UPDATE planejamento_aquisicao SET unidade = 'ULOG' WHERE unidade IS NULL")
    # Tornar a coluna NOT NULL após popular os dados
    op.alter_column('planejamento_aquisicao', 'unidade', nullable=False)
    
    op.add_column('users_safs', sa.Column('unidade', sa.String(length=60), nullable=True))
    # Atualizar registros existentes com valor padrão
    op.execute("UPDATE users_safs SET unidade = 'ULOG' WHERE unidade IS NULL")
    # Tornar a coluna NOT NULL após popular os dados
    op.alter_column('users_safs', 'unidade', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_safs', 'unidade')
    op.drop_column('planejamento_aquisicao', 'unidade')
    op.drop_column('itens_catalogo', 'embalagem')
    op.drop_column('itens_catalogo', 'marca')
    op.drop_column('itens_catalogo', 'unidade')
    op.drop_table('item_processo')
    # ### end Alembic commands ###
