"""adicionar_tabela_responsaveis_tecnicos_e_foreign_key

Revision ID: 4c52c6e97ca8
Revises: bb561c539754
Create Date: 2025-08-21 16:39:08.328867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c52c6e97ca8'
down_revision: Union[str, None] = 'bb561c539754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsaveis_tecnicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_res_tec', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('itens_catalogo', sa.Column('responsavel_tecnico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itens_catalogo', 'responsaveis_tecnicos', ['responsavel_tecnico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itens_catalogo', type_='foreignkey')
    op.drop_column('itens_catalogo', 'responsavel_tecnico_id')
    op.drop_table('responsaveis_tecnicos')
    # ### end Alembic commands ###
