"""Adiciona campo username na tabela users_safs

Revision ID: 5a04f046d1c4
Revises: 3d9eec300d52
Create Date: 2025-07-22 13:34:24.921875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a04f046d1c4'
down_revision: Union[str, None] = '3d9eec300d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_safs', sa.Column('username', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users_safs', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_safs', type_='unique')
    op.drop_column('users_safs', 'username')
    # ### end Alembic commands ###
