"""Add codigo_master column to planejamento_aquisicao

Revision ID: 6558fab46e4d
Revises: 1dea829283ae
Create Date: 2025-07-19 12:53:02.881364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6558fab46e4d'
down_revision: Union[str, None] = '1dea829283ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planejamento_aquisicao', sa.Column('codigo_master', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planejamento_aquisicao', 'codigo_master')
    # ### end Alembic commands ###
