"""Cria tabela catalogo e aqusição

Revision ID: 9c27e61cdef9
Revises: 999252dbe15a
Create Date: 2025-07-09 14:58:31.549050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c27e61cdef9'
down_revision: Union[str, None] = '999252dbe15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_master', sa.String(length=20), nullable=False),
    sa.Column('codigo_aghu_hu', sa.String(length=20), nullable=True),
    sa.Column('codigo_aghu_meac', sa.String(length=20), nullable=True),
    sa.Column('catmat', sa.String(length=20), nullable=True),
    sa.Column('codigo_ebserh', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('apresentacao', sa.String(length=100), nullable=True),
    sa.Column('classificacao_xyz', sa.String(length=10), nullable=True),
    sa.Column('comprador', sa.String(length=100), nullable=True),
    sa.Column('controlador', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_master')
    )
    op.create_table('planejamento_aquisicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('objeto_aquisicao', sa.String(length=255), nullable=False),
    sa.Column('numero_processo_planejamento', sa.String(length=50), nullable=False),
    sa.Column('numero_item', sa.String(length=10), nullable=False),
    sa.Column('status_processo_planejamento', sa.String(length=50), nullable=False),
    sa.Column('numero_processo_compra_centralizada', sa.String(length=50), nullable=True),
    sa.Column('status_compra_centralizada', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planejamento_aquisicao')
    op.drop_table('itens_catalogo')
    # ### end Alembic commands ###
