"""Adicionar relacionamentos many-to-many para usuarios

Revision ID: f44eabf6633e
Revises: 472cd77349fd
Create Date: 2025-08-11 10:48:08.712082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44eabf6633e'
down_revision: Union[str, None] = '472cd77349fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprador_processo',
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['users_safs.id'], name='fk_comprador_processo_user_id'),
    sa.ForeignKeyConstraint(['processo_id'], ['planejamento_aquisicao.id'], name='fk_comprador_processo_processo_id'),
    sa.PrimaryKeyConstraint('comprador_id', 'processo_id')
    )
    op.create_table('comprador_item',
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['users_safs.id'], name='fk_comprador_item_user_id'),
    sa.ForeignKeyConstraint(['item_id'], ['itens_catalogo.id'], name='fk_comprador_item_item_id'),
    sa.PrimaryKeyConstraint('comprador_id', 'item_id')
    )
    op.create_table('controlador_item',
    sa.Column('controlador_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controlador_id'], ['users_safs.id'], name='fk_controlador_item_user_id'),
    sa.ForeignKeyConstraint(['item_id'], ['itens_catalogo.id'], name='fk_controlador_item_item_id'),
    sa.PrimaryKeyConstraint('controlador_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controlador_item')
    op.drop_table('comprador_item')
    op.drop_table('comprador_processo')
    # ### end Alembic commands ###
