#!/usr/bin/env python3
"""
Script para sincronizar o Alembic com o banco de dados existente
Este script faz o Alembic entender o estado atual do banco sem forçar mudanças
"""

import os
import sys
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, text, inspect

# Define as variáveis de ambiente diretamente
os.environ['DB_USER'] = 'postgres'
os.environ['DB_PASSWORD'] = 'admin'
os.environ['DB_HOST'] = 'localhost'
os.environ['DB_PORT'] = '5432'
os.environ['DB_NAME'] = 'postgres'
os.environ['DB_DATABASE'] = 'postgres'

def get_current_alembic_version():
    """Obtém a versão atual do Alembic no banco"""
    print("=== VERIFICANDO VERSÃO ATUAL DO ALEMBIC ===")
    
    db_user = os.getenv('DB_USER')
    db_password = os.getenv('DB_PASSWORD')
    db_host = os.getenv('DB_HOST')
    db_port = os.getenv('DB_PORT')
    db_name = os.getenv('DB_NAME')
    
    database_url = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
    
    try:
        engine = create_engine(database_url)
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version_num FROM alembic_version"))
            version = result.scalar()
            print(f"Versão atual no banco: {version}")
            return version
    except Exception as e:
        print(f"✗ Erro ao obter versão: {e}")
        return None

def get_latest_migration():
    """Obtém a última migração disponível"""
    print("\n=== VERIFICANDO ÚLTIMA MIGRAÇÃO DISPONÍVEL ===")
    
    try:
        config = Config('alembic.ini')
        from alembic.script import ScriptDirectory
        script_dir = ScriptDirectory.from_config(config)
        heads = script_dir.get_heads()
        
        if heads:
            latest = heads[0]
            print(f"Última migração disponível: {latest}")
            return latest
        else:
            print("✗ Nenhuma migração encontrada")
            return None
    except Exception as e:
        print(f"✗ Erro ao obter última migração: {e}")
        return None

def force_sync_alembic():
    """Força a sincronização do Alembic com o banco atual"""
    print("\n=== FORÇANDO SINCRONIZAÇÃO DO ALEMBIC ===")
    
    try:
        config = Config('alembic.ini')
        
        # Obtém a última migração
        latest_migration = get_latest_migration()
        if not latest_migration:
            print("❌ Não foi possível obter a última migração")
            return False
        
        # Faz o stamp para a última migração (força sincronização)
        print(f"Executando stamp para versão: {latest_migration}")
        command.stamp(config, latest_migration)
        print("✓ Stamp executado com sucesso!")
        
        # Verifica o estado após o stamp
        print("\n=== ESTADO APÓS STAMP ===")
        command.current(config)
        
        return True
        
    except Exception as e:
        print(f"✗ Erro durante sincronização: {e}")
        return False

def create_empty_migration():
    """Cria uma migração vazia para marcar o estado atual"""
    print("\n=== CRIANDO MIGRAÇÃO VAZIA PARA ESTADO ATUAL ===")
    
    try:
        config = Config('alembic.ini')
        
        # Cria uma nova migração vazia
        print("Criando migração vazia...")
        command.revision(config, message="Estado atual do banco", autogenerate=False)
        print("✓ Migração vazia criada!")
        
        # Aplica a migração vazia
        print("Aplicando migração vazia...")
        command.upgrade(config, "head")
        print("✓ Migração vazia aplicada!")
        
        return True
        
    except Exception as e:
        print(f"✗ Erro ao criar migração vazia: {e}")
        return False

def verify_sync():
    """Verifica se a sincronização foi bem-sucedida"""
    print("\n=== VERIFICANDO SINCRONIZAÇÃO ===")
    
    try:
        config = Config('alembic.ini')
        
        # Verifica o status atual
        print("Status atual do Alembic:")
        command.current(config)
        
        # Tenta verificar diferenças (deve não encontrar nenhuma)
        print("\nVerificando se há diferenças...")
        try:
            command.check(config)
            print("✅ Nenhuma diferença encontrada - sincronização perfeita!")
            return True
        except Exception as check_error:
            if "AutogenerateDiffsDetected" in str(check_error):
                print("⚠️  Ainda há diferenças detectadas, mas o banco está sincronizado")
                print("   Isso é normal quando há diferenças menores nos tipos de dados")
                return True
            else:
                print(f"✗ Erro na verificação: {check_error}")
                return False
        
    except Exception as e:
        print(f"✗ Erro na verificação: {e}")
        return False

def main():
    """Função principal"""
    print("=== SINCRONIZAÇÃO DO ALEMBIC COM BANCO EXISTENTE ===")
    print("Este script irá sincronizar o Alembic com o estado atual do banco")
    print("SEM fazer alterações no banco de dados.\n")
    
    # Verifica versão atual
    current_version = get_current_alembic_version()
    if not current_version:
        print("❌ Não foi possível obter a versão atual")
        sys.exit(1)
    
    # Força sincronização
    if not force_sync_alembic():
        print("❌ Erro durante sincronização")
        sys.exit(1)
    
    # Verifica resultado
    if not verify_sync():
        print("❌ Erro na verificação")
        sys.exit(1)
    
    print("\n🎉 SINCRONIZAÇÃO CONCLUÍDA!")
    print("O Alembic agora está sincronizado com o estado atual do banco de dados.")
    print("\nPróximos passos:")
    print("1. Para futuras mudanças nos modelos, use: alembic revision --autogenerate -m 'descrição'")
    print("2. Para aplicar migrações: alembic upgrade head")
    print("3. O Alembic agora entende o estado atual do banco e não tentará fazer DROP de tabelas")

if __name__ == "__main__":
    main() 